{
    "id": "CWE-248",
    "name": "Uncaught Exception",
    "href": "AIP/quality-standards/OMG-ASCQM/items/CWE-248",
    "url": "https://cwe.mitre.org/data/definitions/248.html",
    "description": "An exception is thrown from a function, but it is not caught.",
    "isoPatterns": [
        {
            "name": "ASCQM Catch Exceptions"
        }
    ],
    "count": 2,
    "qualityRules": {
        "name": "Quality Rules in numeric ID order",
        "href": "AIP/quality-standards/OMG-ASCQM/items/CWE-248/quality-rules"
    },
    "qualityTemplates": {
        "name": "Quality Templates in numeric ID order",
        "href": "AIP/quality-standards/OMG-ASCQM/items/CWE-248/quality-templates"
    }
}
