{
    "id": "CWE-584",
    "name": "Return Inside Finally Block",
    "href": "Echo/quality-standards/CWE/items/CWE-584",
    "url": "https://cwe.mitre.org/data/definitions/584.html",
    "description": "The code has a return statement inside a finally block, which will cause any thrown exception in the try block to be discarded.",
    "isoPatterns": null,
    "count": 3,
    "qualityRules": {
        "name": "Quality Rules in numeric ID order",
        "href": "Echo/quality-standards/CWE/items/CWE-584/quality-rules"
    }
}
