[
    {
        "id": 1065026,
        "name": "Ensure exception objects are always caught by reference (C++)",
        "href": "AIP/quality-rules/1065026",
        "status": null,
        "critical": false,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 1065034,
        "name": "Avoid throwing an exception object of pointer type (C++)",
        "href": "AIP/quality-rules/1065034",
        "status": null,
        "critical": false,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 1065048,
        "name": "Where multiple handlers are provided in a single try-catch statement or function-try-block, any ellipsis (catch-all) handler shall occur last.",
        "href": "AIP/quality-rules/1065048",
        "status": null,
        "critical": false,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 1065056,
        "name": "Avoid throwing exceptions outside of main()",
        "href": "AIP/quality-rules/1065056",
        "status": null,
        "critical": false,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 1065058,
        "name": "Ensure that there is at least one exception handler to catch-all otherwise unhandled exceptions",
        "href": "AIP/quality-rules/1065058",
        "status": null,
        "critical": false,
        "technologyNames": [
            "C++"
        ]
    }
]
